sudo: required
language: python
services:
  - docker

branches:
  only:
    - master

env:
  global:
    - IMAGE_NAME=jamiehewland/alpine-pypy-build
    - secure: "DCHokMpVW2tZFOD33RaH2Z768FTdyYh+j08CTRp7XRg2NIZf/NQacxchUM3xmsb711wEag10m06I3lBk3oBuea/KfmY2gowx1ThzoaZ27hAoDIGwfeem3atgbOEweCGMsxrsPmIXDwKfiJiZ30G8n4uz+uQEi0PS7tO4vIitryvld0ssOJyMMKei+bAv6KqLhIE8dwAiRnXbgQ9mW6mM7cb9tlL17Eu6n/pX+bR4M3qkoH7qGlHhM15EzszEUjN6g7oLxZKK9yABjVt0XxQfbwbBLf9yKgNhBRnkjZUlcNvDIS5hCFh/d6TW4q+zLJy6PpBKL83V80RDimm+JnkfcWKEDwLAfEmb1dpqIjQ4Id0Rp9v/3XobvyhYLNtzCMk8Qoly6hOkLTbbKgWuWN2d51ASxJ6iLswTjcKIkOPAbTdXV0QMgGfa7vjdgDrxLyVTaxYBk4BAIfGkWU01Oq4FMNHuPCr/fQKtWEvSVBXi7BRw1QviOScOr8eUc/QU+iawH+7WkScQLFnIsxO8yoXpdlmmQnKSTBk0KUS9DmBqYOYnyU1yPagq7/sdNBfKmgfV+rGhszPOw7I14SG08ApwWLuiauv7DRReeeoPX4oYjyRQr7Ue2rK3Igh4vDGJwxeXzqDx9hS9zNlV4xl2KWSDxxdIKZmE5SOiWXojCxiT+LY="
  matrix:
    - PYPY_VERSION=2 ALPINE_VERSION=3.6 VARIANT=          VERSION_LATEST=
    - PYPY_VERSION=2 ALPINE_VERSION=3.6 VARIANT=bootstrap VERSION_LATEST=
    - PYPY_VERSION=3 ALPINE_VERSION=3.6 VARIANT=          VERSION_LATEST=1
    - PYPY_VERSION=3 ALPINE_VERSION=3.6 VARIANT=bootstrap VERSION_LATEST=1

before_script:
  - cd "$PYPY_VERSION"
  - image="$IMAGE_NAME:$PYPY_VERSION${VARIANT:+-$VARIANT}-alpine$ALPINE_VERSION"
  - dockerfile="alpine$ALPINE_VERSION/${VARIANT:+$VARIANT/}Dockerfile"
  - version="$(awk '$2 == "PYPY_VERSION" { print $3; exit }' "$dockerfile")"
  - echo "Building image '$image' from Dockerfile at $dockerfile with version '$version'"
  - docker pull "$image" || true

script:
  - docker build --pull --cache-from "$image" -t "$image" -f "$dockerfile" .
  - pip install docker-ci-deploy==0.3.0
  - dcd --version "$PYPY_VERSION-$version" --version-semver ${VERSION_LATEST:+--version-latest} --dry-run "$image"

after_script:
  - docker images

before_deploy:
  - pip install docker-ci-deploy==0.3.0
  - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: dcd --version "$PYPY_VERSION-$version" --version-semver ${VERSION_LATEST:+--version-latest} "$image"
  on:
    branch: master
